//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Botintiedot
    {
        public int BottiID { get; set; }
        public Nullable<int> KayttajaID { get; set; }
        public Nullable<System.DateTime> BottiAika { get; set; }
        public Nullable<int> BottiHalkoja { get; set; }
        public Nullable<int> BottiKokemuspisteita { get; set; }
        public Nullable<int> BottiRahaaTunnissa { get; set; }
        public Nullable<int> BottiTaitotasoNousu { get; set; }
    
        public virtual Bottaajantiedot Bottaajantiedot { get; set; }
    }
}
