//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BottikantaEntities : DbContext
    {
        public BottikantaEntities()
            : base("name=BottikantaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Botintiedot> Botintiedot { get; set; }
        public virtual DbSet<Bottaajantiedot> Bottaajantiedot { get; set; }
        public virtual DbSet<Bottipelaaja> Bottipelaaja { get; set; }
    }
}
