//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottaajantiedot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottaajantiedot()
        {
            this.Botintiedot = new HashSet<Botintiedot>();
        }
    
        public int KayttajaID { get; set; }
        public Nullable<int> BottaajaID { get; set; }
        public string Kayttajatunnus { get; set; }
        public Nullable<int> Pinkoodi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Botintiedot> Botintiedot { get; set; }
        public virtual Bottipelaaja Bottipelaaja { get; set; }
    }
}
